version: "3.7"

services:

  business:
    image: business:latest
    build:
      context: business
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      COUNTER_SERVICE_URL: "http://counters"
    depends_on:
      - counters

  counters:
    image: counters:latest
    build:
      context: counter
      dockerfile: counter.dockerfile
    ports:
      - "5001:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DatabaseOptions__CounterDatabase: "Server=mssqlserver;Database=Counter;User=sa;Password=Your_password123;"
      HangfireOptions__ConnectionString: "Server=mssqlserver;Database=Counter;User=sa;Password=Your_password123;"
      SwaggerOptions__ApplicationTitle: "Ant Counter Api Docker"
      LoggingOptions__ApplicationName: "Ant Counter Api Docker"
      LoggingOptions__ElasticSearchUrl: "http://elasticsearch:9200"
      ElasticApm__ServiceName: "Counter Api"
      ElasticApm__ServerUrls: "http://apm-server:8200"
      ElasticApm__Environment: "Docker"
      Serilog__MinimumLevel__Override__Elastic.Apm: "Error"
    depends_on:
      - mssqlserver
      - apm-server
      - elasticsearch

  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    volumes:
      - ./counter/Ant.Volumes/mssqlserver/mssql/data:/var/opt/mssql/data
      - ./counter/Ant.Volumes/mssqlserver/sqlserver:/var/opt/mssqlserver

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.15.2
    depends_on:
      - elasticsearch
      - kibana
    cap_add: [ "CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID" ]
    cap_drop: [ "ALL" ]
    ports:
      - "8200:8200"
    command: >
      apm-server -e
        -E apm-server.rum.enabled=true
        -E setup.kibana.host=kibana:5601
        -E setup.template.settings.index.number_of_replicas=0
        -E apm-server.kibana.enabled=true
        -E apm-server.kibana.host=kibana:5601
        -E output.elasticsearch.hosts=["elasticsearch:9200"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      bootstrap.memory_lock: "true"
      cluster.name: "docker-cluster"
      cluster.routing.allocation.disk.threshold_enabled: "false"
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-XX:UseAVX=2 -Xms1g -Xmx1g"
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - ./counter/Ant.Volumes/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
